name: GitHub Actions Deploy Nodeapp-into-AKS
run-name: ${{github.actor}} is triggering the GitHub Actions 🚀
on: 
  push:
    branches: ["main"]
#   workflow_dispatch:
permissions:
   id-token: write
   contents: read
   actions: read
  
jobs:
  BuildAndPushImageToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{secrets.ACS_USERNAME}}
          password: ${{secrets.ACS_PASSWD}}
          # Container registry server url
          login-server:  ${{vars.ACS_LOGIN_SERVER}}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{vars.ACS_LOGIN_SERVER}}/${{vars.IMAGE_NAME}}:${{github.sha}}
          file: ./Dockerfile
          
  DeployAppToAKS:
    runs-on: ubuntu-latest
    needs: [BuildAndPushImageToACR]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # github actions login azure
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # github actions login k8s
      - name: setup kubernetes login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.24'
      
      # github actions set k8s context
      - name: set k8s context
        uses: azure/aks-set-context@v3
        with:
           resource-group: ${{vars.RESOURCE_GROUP}}
           cluster-name: ${{vars.AKS_CLUSTER_NAME}}
           subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           admin: 'false'
           use-kubelogin: 'true'
           
      # deploy our node app depmoyment.yaml and sevice.yaml to k8s cluster
      - name: deploy node app to k8s
        uses: Azure/k8s-deploy@v4
        with:
           namespace: 'myapp'
           manifests: |
              kubernetes/hello-world-deployment.yaml
              kubernetes/hello-world-service.yaml
           images: ${{vars.ACS_LOGIN_SERVER}}/${{vars.IMAGE_NAME}}:${{github.sha}}


